import 'package:hive/hive.dart';

part 'person.g.dart';
// This will be name of the file which will be autogenerated by hive.

//file name and class name and part will be same name:

@HiveType(typeId: 1)
class Person {
  Person({required this.name, required this.age});

  @HiveField(0)
  String? name;

  @HiveField(1)
  int? age;
}

// To create a part.g file run this below command:
// dart run build_runner build